-- Verified root academic units: Ankara University, Hacettepe University, Gazi University
-- Sources were official university pages checked on 2026-08-06.

insert into public.academic_unit_import_staging
  (university_name, parent_name, unit_name, unit_type, source_url)
values
  -- Ankara University faculties
  ('Ankara Üniversitesi', null, 'Dil ve Tarih-Coğrafya Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Diş Hekimliği Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Eczacılık Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Eğitim Bilimleri Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Fen Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Güzel Sanatlar Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Hemşirelik Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Hukuk Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'İlahiyat Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'İletişim Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Mühendislik Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Sağlık Bilimleri Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Siyasal Bilgiler Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Spor Bilimleri Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Tıp Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Uygulamalı Bilimler Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Veteriner Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  ('Ankara Üniversitesi', null, 'Ziraat Fakültesi', 'fakulte', 'https://uyum.ankara.edu.tr/fakulteler/'),
  -- Ankara University institutes and conservatory
  ('Ankara Üniversitesi', null, 'Eğitim Bilimleri Enstitüsü', 'enstitu', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),
  ('Ankara Üniversitesi', null, 'Fen Bilimleri Enstitüsü', 'enstitu', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),
  ('Ankara Üniversitesi', null, 'Gıda Güvenliği Enstitüsü', 'enstitu', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),
  ('Ankara Üniversitesi', null, 'Sağlık Bilimleri Enstitüsü', 'enstitu', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),
  ('Ankara Üniversitesi', null, 'Sosyal Bilimler Enstitüsü', 'enstitu', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),
  ('Ankara Üniversitesi', null, 'Su Yönetimi Enstitüsü', 'enstitu', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),
  ('Ankara Üniversitesi', null, 'Türk İnkılap Tarihi Enstitüsü', 'enstitu', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),
  ('Ankara Üniversitesi', null, 'Devlet Konservatuvarı', 'konservatuvar', 'https://www.erasmus.ankara.edu.tr/anlasmalar-listesi/'),

  -- Hacettepe University faculties
  ('Hacettepe Üniversitesi', null, 'Diş Hekimliği Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Eczacılık Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Edebiyat Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Eğitim Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Fen Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Fizik Tedavi ve Rehabilitasyon Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Güzel Sanatlar Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Hemşirelik Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Hukuk Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'İktisadi ve İdari Bilimler Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'İletişim Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Mühendislik Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Tıp Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Sağlık Bilimleri Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Spor Bilimleri Fakültesi', 'fakulte', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  -- Hacettepe institutes, conservatory and schools
  ('Hacettepe Üniversitesi', null, 'Aşı Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Atatürk İlkeleri ve İnkılap Tarihi Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Bilişim Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Çocuk Sağlığı Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Eğitim Bilimleri Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Fen Bilimleri Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Güzel Sanatlar Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Halk Sağlığı Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Nörolojik Bilimler ve Psikiyatri Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Nüfus Etütleri Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Nükleer Bilimler Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Onkoloji Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Sağlık Bilimleri Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Sosyal Bilimler Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Türkiyat Araştırmaları Enstitüsü', 'enstitu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Ankara Devlet Konservatuvarı', 'konservatuvar', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Yabancı Diller Yüksekokulu', 'yuksekokul', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Mesleki Teknoloji Yüksekokulu', 'yuksekokul', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Hacettepe Ankara Sanayi Odası 1. OSB Meslek Yüksekokulu', 'meslek_yuksekokulu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Başkent OSB Teknik Bilimler Meslek Yüksekokulu', 'meslek_yuksekokulu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Sağlık Hizmetleri Meslek Yüksekokulu', 'meslek_yuksekokulu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),
  ('Hacettepe Üniversitesi', null, 'Sosyal Bilimler Meslek Yüksekokulu', 'meslek_yuksekokulu', 'https://www.hacettepe.edu.tr/hakkinda/iletisim'),

  -- Gazi University faculties and vocational schools
  ('Gazi Üniversitesi', null, 'Diş Hekimliği Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Eczacılık Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Fen Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Gazi Eğitim Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Mühendislik Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Mimarlık Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Spor Bilimleri Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Sağlık Bilimleri Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Teknoloji Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Tıp Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Uygulamalı Bilimler Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Hemşirelik Fakültesi', 'fakulte', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Teknik Bilimler Meslek Yüksekokulu', 'meslek_yuksekokulu', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'TUSAŞ-Kazan Meslek Yüksekokulu', 'meslek_yuksekokulu', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Sağlık Hizmetleri Meslek Yüksekokulu', 'meslek_yuksekokulu', 'https://gazi.edu.tr/view/faculties-and-vocational-schools'),
  ('Gazi Üniversitesi', null, 'Bilişim Enstitüsü', 'enstitu', 'https://sgk.gazi.edu.tr/view/page/291466/birim-stratejik-planlari'),
  ('Gazi Üniversitesi', null, 'Eğitim Bilimleri Enstitüsü', 'enstitu', 'https://sgk.gazi.edu.tr/view/page/291466/birim-stratejik-planlari'),
  ('Gazi Üniversitesi', null, 'Fen Bilimleri Enstitüsü', 'enstitu', 'https://sgk.gazi.edu.tr/view/page/291466/birim-stratejik-planlari'),
  ('Gazi Üniversitesi', null, 'Sağlık Bilimleri Enstitüsü', 'enstitu', 'https://sgk.gazi.edu.tr/view/page/291466/birim-stratejik-planlari')
on conflict do nothing;

select * from public.import_academic_units();
